### ISSUE TITLE
Execution failed for task ':app:processDebugResources'

### ISSUE THREAD

**Issue by VladsGG** [bradmartin/nativescript-advanced-webview#31]
I got this build error after installing AdvancedWebView Plugin

> C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\4cfb5a08e8368816ef3645c7e80ffb22\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
> C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\4cfb5a08e8368816ef3645c7e80ffb22\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.
> C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\4cfb5a08e8368816ef3645c7e80ffb22\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
> C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\4cfb5a08e8368816ef3645c7e80ffb22\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontStyle not found.
> C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\4cfb5a08e8368816ef3645c7e80ffb22\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/font not found.
> C:\Users\user\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\4cfb5a08e8368816ef3645c7e80ffb22\res\values\values.xml:252:5-69: AAPT: error: resource android:attr/fontWeight not found.
> E:\NativeScript\simpleapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
> E:\NativeScript\simpleapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
> E:\NativeScript\simpleapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
> E:\NativeScript\simpleapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:501: error: resource android:attr/fontStyle not found.
> E:\NativeScript\simpleapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:501: error: resource android:attr/font not found.
> E:\NativeScript\simpleapp\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:501: error: resource android:attr/fontWeight not found.
> error: failed linking references.
> Failed to execute aapt

**Comment by VladsGG** [comment]
(Cont..)

com.android.ide.common.process.ProcessException: Failed to execute aapt
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
	at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
	at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)

**Comment by ephraimlambarte** [comment]
im having the same error when i added nativescript-firebase-plugin on my nativescript-vue project

**Comment by triniwiz** [comment]
The plugin needs to be upgraded to added proper {N} v4 support but if you can't wait , simply open the `include.gradle` in the node_modules for this plugin and remove everything between `android{}` https://github.com/bradmartin/nativescript-advanced-webview/blob/master/platforms/android/include.gradle#L3-L7 delete your platforms directory then try building again 😄

**Comment by cristianmiranda** [comment]
I'm having the same issue with firebase. Any updates?

**Comment by cristianmiranda** [comment]
UPDATE: I was having this issue with Android API 23, I tested on 26 and everything worked fine.

**Comment by cristianmiranda** [comment]
UPDATE 2: I ended up having the same issue on another pc while trying to run the same project on the same Android API emulator. I finally fixed it adding this in my app.gradle:

```
dependencies {
    compile 'com.android.support:appcompat-v7:26.0.0'
    compile 'com.android.support:support-v4:26.0.0'
}
```
Hope it helps!

**Comment by NikolayBa** [comment]
Thanks @cristianmiranda ! I was struggling with the same issue for the past week and your suggestion worked perfectly!

**Comment by bradmartin** [comment]
I've successfully ran the demo, so going to close this. Issues with dependencies and different native libs being loaded via gradle is a tricky situation and has to be handled case by case unfortunately. You can get into some very complex gradle logic to handle these scenarios even.
